# Data-X Fall 2018: Machine Learning


**Authors:** Sana Iqbal (Part 1, 2, 3)


In this homework, you will do some exercises with prediction.


In [374]:
import numpy as np
import pandas as pd

In [375]:
 # machine learning libraries
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
#import xgboost as xgb

## Part 1



__ 1. Read __`diabetesdata.csv`__ file into a pandas dataframe. 
About the data: __

1. __TimesPregnant__: Number of times pregnant 
2. __glucoseLevel__: Plasma glucose concentration a 2 hours in an oral glucose tolerance test 
3. __BP__: Diastolic blood pressure (mm Hg)  
5. __insulin__: 2-Hour serum insulin (mu U/ml) 
6. __BMI__: Body mass index (weight in kg/(height in m)^2) 
7. __pedigree__: Diabetes pedigree function 
8. __Age__: Age (years) 
9. __IsDiabetic__: 0 if not diabetic or 1 if diabetic) 








In [376]:
#Read data & print it
data = pd.read_csv('diabetesdata.csv')
data.head()

    

TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  IsDiabetic
0              6         148.0  72        0  33.6     0.627  50.0           1
1              1           NaN  66        0  26.6     0.351  31.0           0
2              8         183.0  64        0  23.3     0.672   NaN           1
3              1           NaN  66       94  28.1     0.167  21.0           0
4              0         137.0  40      168  43.1     2.288  33.0           1

**2. Calculate the percentage of NaN values in each column.**

In [377]:
def missing_values_table(df):
        mis_val_percent = df.isnull().sum() / len(df)
        mis_val_percent = mis_val_percent.to_frame()
        mis_val_table_ren_columns = mis_val_percent.rename(columns = {0 : 'Percentage Null'})
        return mis_val_table_ren_columns
    
NullsPerColumn = missing_values_table(data)
NullsPerColumn

Percentage Null
TimesPregnant         0.000000
glucoseLevel          0.044271
BP                    0.000000
insulin               0.000000
BMI                   0.000000
Pedigree              0.000000
Age                   0.042969
IsDiabetic            0.000000

In [378]:
###RUN THIS CELL BUT DO NOT ALTER IT 
assert all(NullsPerColumn.columns == ['Percentage Null'])
assert NullsPerColumn['Percentage Null'][-2] ==  0.04296875

**3. Calculate the TOTAL percent of ROWS with NaN values in the dataframe (make sure values are floats).**

In [379]:
nanrow = data.isnull().any(axis=1).sum()
PercentNull = nanrow/len(data)
PercentNull

0.08333333333333333

**4. Split __`data`__  into  __`train_df`__ and __`test_df`__  with 15% test split.**


In [380]:
#split values
from sklearn.model_selection import train_test_split
train_df, test_df = train_test_split(data,test_size=0.15)


In [381]:
###RUN THIS CELL BUT DO NOT ALTER IT 
np.testing.assert_almost_equal(float(len(train_df))/float(len(data)), 0.8489583333333334, 1)
np.testing.assert_almost_equal(float(len(test_df))/float(len(data)), 0.15104166666666666, 1)



**5. Replace the Nan values in  __`train_df`__ and __`test_df`__  with the mean of EACH feature.**

In [382]:
train_df['glucoseLevel'].fillna(train_df['glucoseLevel'].dropna().mean(), inplace=True)
train_df['Age'].fillna(train_df['Age'].dropna().mean(), inplace=True)
test_df['glucoseLevel'].fillna(test_df['glucoseLevel'].dropna().mean(), inplace=True)
test_df['Age'].fillna(test_df['Age'].dropna().mean(), inplace=True)

/Users/aaronchan/anaconda3/envs/data-x/lib/python3.6/site-packages/pandas/core/generic.py:5430: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [383]:
###RUN THIS CELL BUT DO NOT ALTER IT 
assert sum(train_df.isnull().sum()) == 0 
assert sum(test_df.isnull().sum()) == 0 


**6. Split __`train_df`__ & __`test_df`__   into  __`X_train`__, __`Y_train`__  and __`X_test`__, __`Y_test`__. __`Y_train`__  and __`Y_test`__ should only have the column we are trying to predict,  __`IsDiabetic`__.**

In [384]:
X_train = train_df.drop("IsDiabetic", axis=1)
Y_train = train_df["IsDiabetic"]  
X_test  = test_df.drop("IsDiabetic", axis=1)
Y_test = test_df["IsDiabetic"]  

In [385]:
###RUN THIS CELL BUT DO NOT ALTER IT 
assert [X_train.shape, Y_train.shape, X_test.shape,Y_test.shape] == [(652, 7), (652,), (116, 7),(116,)]


**7.Use this dataset to train perceptron, logistic regression and random forest models using 15% test split. Report training and test accuracies.**

In [386]:
# Logistic Regression
np.random.seed(138)
#trainset
logreg = LogisticRegression()
logreg.fit(X_train, Y_train)
logreg_train_acc = logreg.score(X_train, Y_train) 
print ('logreg training acuracy= ',logreg_train_acc)

#testset
logreg_test_acc = logreg.score(X_test, Y_test)
print ('logreg test acuracy= ',logreg_test_acc)

logreg training acuracy=  0.7822085889570553
logreg test acuracy=  0.7327586206896551


In [387]:
# Perceptron
#trainset
perceptron = Perceptron()
perceptron.fit(X_train, Y_train)
perceptron_train_acc = perceptron.score(X_train, Y_train) 
print ('perceptron training acuracy= ',perceptron_train_acc)

#testset
perceptron_test_acc = perceptron.score(X_test, Y_test) 
print('perceptron test accuracy= ',perceptron_test_acc)


perceptron training acuracy=  0.5276073619631901
perceptron test accuracy=  0.5086206896551724


/Users/aaronchan/anaconda3/envs/data-x/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.perceptron.Perceptron'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


In [388]:
# Adaboost
#trainset
adaboost = AdaBoostClassifier()
adaboost.fit(XX_train, YY_train)
adaboost_train_acc = adaboost.score(X_train, Y_train) 
print ('adaboost training acuracy= ',adaboost_train_acc)

#testset
adaboost_test_acc = adaboost.score(X_test, Y_test) 
print('adaboost test accuracy= ',adaboost_test_acc)

adaboost training acuracy=  0.7914110429447853
adaboost test accuracy=  0.7931034482758621


In [389]:

# Random Forest
#trainset
random_forest = RandomForestClassifier() 
random_forest.fit(X_train, Y_train)
acc_rf = random_forest.score(X_train, Y_train)  
random_forest_train_acc = str(round(acc_rf*100,2))
#testset
acc_rftest = random_forest.score(X_test, Y_test)  
random_forest_test_acc = str(round(acc_rftest*100,2))
print('random_forest training acuracy= ',random_forest_train_acc)
print('random_forest test accuracy= ',random_forest_test_acc)

random_forest training acuracy=  98.31
random_forest test accuracy=  69.83


**8. Is mean imputation is the best type of imputation to use? Why or why not? What are some other ways to impute the data?**

No, it is not. It does not preserve the relationships among variables. Other ways are Hot deck imputation and Cold deck imputation. (To chose a value from an individual in the sample who has similar values on other variables)

## Part 2


__1.Add columns __`BMI_band`__ & __`Pedigree_band`__  to  __`Data`__  by cutting __`BMI`__ & __`Pedigree`__ into 3 intervals. PRINT the first 5 rows of__`data`__.__


In [390]:
data['BMI_band'] = pd.cut(data['BMI'], 3)
data['Pedigree_band'] = pd.cut(data['Pedigree'], 3)
data.head(5)


TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  IsDiabetic  \
0              6         148.0  72        0  33.6     0.627  50.0           1   
1              1           NaN  66        0  26.6     0.351  31.0           0   
2              8         183.0  64        0  23.3     0.672   NaN           1   
3              1           NaN  66       94  28.1     0.167  21.0           0   
4              0         137.0  40      168  43.1     2.288  33.0           1   

           BMI_band    Pedigree_band  
0  (22.367, 44.733]  (0.0757, 0.859]  
1  (22.367, 44.733]  (0.0757, 0.859]  
2  (22.367, 44.733]  (0.0757, 0.859]  
3  (22.367, 44.733]  (0.0757, 0.859]  
4  (22.367, 44.733]    (1.639, 2.42]

__1a. Print the category intervals for __`BMI_band`__ & __`Pedigree_band`.

In [391]:
print('BMI_Band_Interval:', data['BMI_band'].unique())
print()
print('Pedigree_band:', data['Pedigree_band'].unique())

                                                        

BMI_Band_Interval: [(22.367, 44.733], (-0.0671, 22.367], (44.733, 67.1]]
Categories (3, interval[float64]): [(-0.0671, 22.367] < (22.367, 44.733] < (44.733, 67.1]]

Pedigree_band: [(0.0757, 0.859], (1.639, 2.42], (0.859, 1.639]]
Categories (3, interval[float64]): [(0.0757, 0.859] < (0.859, 1.639] < (1.639, 2.42]]


__2. Group __`data`__ by __`Pedigree_band`__ & determine ratio of diabetic in each band.__

In [392]:
 
pedigree_DiabeticRatio = data.groupby(['Pedigree_band'], as_index=False)\
                    .mean().sort_values(by='Pedigree_band', ascending=True)
print(pedigree_DiabeticRatio)

     Pedigree_band  TimesPregnant  glucoseLevel         BP     insulin  \
0  (0.0757, 0.859]       3.870073    120.191424  68.757664   75.702190   
1   (0.859, 1.639]       3.932432    125.500000  72.486486  105.878378   
2    (1.639, 2.42]       1.222222    145.000000  67.777778  177.222222   

         BMI  Pedigree        Age  IsDiabetic  
0  31.659562  0.384975  33.307339    0.327007  
1  34.739189  1.090770  34.375000    0.540541  
2  34.755556  1.997333  28.555556    0.444444  


__2a. Group  __`data`__ by __`BMI_band`__ & determine ratio of diabetic in each band.__

In [393]:
BMI_DiabeticRatio = data.groupby(['BMI_band'], as_index=False)\
                    .mean().sort_values(by='BMI', ascending=True)
print(BMI_DiabeticRatio)
 


            BMI_band  TimesPregnant  glucoseLevel         BP     insulin  \
0  (-0.0671, 22.367]       2.568627    102.297872  54.803922   36.823529   
1   (22.367, 44.733]       3.964758    121.767228  69.566814   81.449339   
2     (44.733, 67.1]       3.388889    132.470588  80.638889  109.472222   

         BMI  Pedigree        Age  IsDiabetic  
0  16.194118  0.380255  30.591837    0.039216  
1  32.284875  0.475261  33.537634    0.358297  
2  48.844444  0.537639  33.800000    0.611111  


In [394]:
###RUN THIS CELL BUT DO NOT ALTER IT 
assert BMI_DiabeticRatio['IsDiabetic'][1] == 0.35829662261380324
assert pedigree_DiabeticRatio['IsDiabetic'][1] == 0.5405405405405406

__3. Convert these features - 'BP','insulin','BMI' and 'Pedigree'   into categorical values by mapping different bands of values of these features to integers 0,1,2.__  
 
HINT: USE pd.cut with bin=3 to create 3 bins



In [395]:
data['BP'] = pd.cut(data['BP'], 3, labels=[0,1,2])
data['insulin'] = pd.cut(data['insulin'], 3, labels=[0,1,2])
data['BMI'] = pd.cut(data['BMI'], 3, labels=[0,1,2])
data['Pedigree'] = pd.cut(data['Pedigree'], 3, labels=[0,1,2])
data.head()


TimesPregnant  glucoseLevel BP insulin BMI Pedigree   Age  IsDiabetic  \
0              6         148.0  1       0   1        0  50.0           1   
1              1           NaN  1       0   1        0  31.0           0   
2              8         183.0  1       0   1        0   NaN           1   
3              1           NaN  1       0   1        0  21.0           0   
4              0         137.0  0       0   1        2  33.0           1   

           BMI_band    Pedigree_band  
0  (22.367, 44.733]  (0.0757, 0.859]  
1  (22.367, 44.733]  (0.0757, 0.859]  
2  (22.367, 44.733]  (0.0757, 0.859]  
3  (22.367, 44.733]  (0.0757, 0.859]  
4  (22.367, 44.733]    (1.639, 2.42]

In [396]:
###RUN THIS CELL BUT DO NOT ALTER IT 
assert sum(data['insulin'])==49
assert sum(data['BMI'])==753
assert sum(data['Pedigree'])==92


__4. Now consider the original dataset again, instead of generalizing the NAN values with the mean of the feature we will try assigning values to NANs based on some hypothesis. For example for age we assume that the relation between BMI and BP of people is a reflection of the age group. We can have 9 types of BMI and BP relations and our aim is to find the median age of each of that group:__

Your Age guess matrix will look like this:  

| BMI | 0       | 1      | 2  |
|-----|-------------|------------- |----- |
| BP  |             |              |      |
| 0   | a00         | a01          | a02  |
| 1   | a10         | a11          | a12  |
| 2   | a20         | a21          |  a22 |


__Create a guess_matrix  for NaN values of *'Age'* ( using 'BMI' and 'BP')  and  *'glucoseLevel'*  (using 'BP' and 'Pedigree') for the given dataset and assign values accordingly to the NaNs in 'Age' or *'glucoseLevel'* .__


Refer to how we guessed age in the titanic notebook in the class.



In [397]:
#age
guess_ages = np.zeros((3,3),dtype=int) 
guess_ages
for i in range(0, 3):
    for j in range(0,3):
        guess_df = data[(data['BMI'] == i)&(data['BP'] == j)]['Age'].dropna()
                        

        # Extract the median age for this group
        # (less sensitive) to outliers
        age_guess = guess_df.median()
          
        # Convert random age float to int
        guess_ages[i,j] = int(age_guess)
    
            
print('Guess_Age table:\n',guess_ages)
print ('\nAssigning age values to NAN age values in the dataset...')
    
for i in range(0, 3):
    for j in range(0, 3):
        data.loc[ (data.Age.isnull()) & (data.BMI == i) \
                & (data.BP == j),'Age'] = guess_ages[i,j]
                    

#glucoseLevel
guess_glucose = np.zeros((3,3),dtype=int) 
guess_glucose
for i in range(0, 3):
    for j in range(0,3):
        guess_dfglu = data[(data['BP'] == i)&(data['Pedigree'] == j)]['glucoseLevel'].dropna()
        
        glu_guess = guess_dfglu.median()
          
        guess_glucose[i,j] = int(glu_guess)
    
            
print('Guess_Age table:\n',guess_glucose)
print ('\nAssigning age values to NAN glucoseLevel values in the dataset...')
    
for i in range(0, 3):
    for j in range(0, 3):
        data.loc[ (data.glucoseLevel.isnull()) & (data.BP == i) \
                & (data.Pedigree == j),'glucoseLevel'] = guess_glucose[i,j]

Guess_Age table:
 [[24 25 55]
 [29 29 37]
 [33 32 31]]

Assigning age values to NAN age values in the dataset...
Guess_Age table:
 [[115 127 137]
 [112 115 149]
 [133 129 159]]

Assigning age values to NAN glucoseLevel values in the dataset...




__5. Now, convert 'glucoseLevel' and 'Age' features also to categorical variables of 4 categories each. PRINT the head of __`data`__ __








In [398]:
data['glucoseLevel'] = pd.cut(data['glucoseLevel'], 4, labels=[0,1,2,3])
data['Age'] = pd.cut(data['Age'], 4, labels=[0,1,2,3])
data.drop('BMI_band',axis=1,inplace=True)
data.drop('Pedigree_band',axis=1,inplace=True)
data.head()

TimesPregnant glucoseLevel BP insulin BMI Pedigree Age  IsDiabetic
0              6            2  1       0   1        0   1           1
1              1            2  1       0   1        0   0           0
2              8            3  1       0   1        0   0           1
3              1            2  1       0   1        0   0           0
4              0            2  0       0   1        2   0           1

__6.Use this dataset (with all features in categorical form) to train perceptron, logistic regression and random forest models using 15% test split. Report training and test accuracies.__


In [399]:
train_df, test_df = train_test_split(data,test_size=0.15)
X_train = train_df.drop("IsDiabetic", axis=1)
Y_train = train_df["IsDiabetic"]  
X_test  = test_df.drop("IsDiabetic", axis=1)
Y_test = test_df["IsDiabetic"]  
X_train.shape, Y_train.shape, X_test.shape

((652, 7), (652,), (116, 7))

In [400]:
# Logistic Regression
#trainset
logreg = LogisticRegression()
logreg.fit(X_train, Y_train)
logreg_train_acc = logreg.score(X_train, Y_train) 
print ('logreg training acuracy= ',logreg_train_acc)

#testset
logreg_test_acc = logreg.score(X_test, Y_test)
print ('logreg test acuracy= ', logreg_test_acc)



logreg training acuracy=  0.7530674846625767
logreg test acuracy=  0.6637931034482759


In [401]:
# Perceptron
#trainset
perceptron = Perceptron()
perceptron.fit(X_train, Y_train)
perceptron_train_acc = perceptron.score(X_train, Y_train) 
print ('perceptron training acuracy= ',perceptron_train_acc)

#testset
perceptron_test_acc = perceptron.score(X_test, Y_test) 
print('perceptron test accuracy= ',perceptron_test_acc)




perceptron training acuracy=  0.6901840490797546
perceptron test accuracy=  0.646551724137931


/Users/aaronchan/anaconda3/envs/data-x/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.perceptron.Perceptron'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


In [402]:
# Random Forest
#trainset
random_forest = RandomForestClassifier() 
random_forest.fit(X_train, Y_train)
acc_rf = random_forest.score(X_train, Y_train)  
random_forest_train_acc = str(round(acc_rf*100,2))
#testset
acc_rftest = random_forest.score(X_test, Y_test)  
random_forest_test_acc = str(round(acc_rftest*100,2))
print('random_forest training acuracy= ',random_forest_train_acc)
print('random_forest test accuracy= ',random_forest_test_acc)


random_forest training acuracy=  86.96
random_forest test accuracy=  69.83
